---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bootstrap.cluster.x-k8s.io
  resources:
  - kubeadmconfigtemplates
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - machinedeployments
  - machinehealthchecks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - machinehealthchecks/status
  verbs:
  - get
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - machines
  - machinesets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - begetmachinetemplates
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - workergroup.in-cloud.io
  resources:
  - nodelabelpolicies
  - wgbootstraptemplates
  - wgmachinetemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - workergroup.in-cloud.io
  resources:
  - nodelabelpolicies/status
  - workergroupclaims/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - workergroup.in-cloud.io
  resources:
  - workergroupclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - workergroup.in-cloud.io
  resources:
  - workergroupclaims/finalizers
  verbs:
  - update
