apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodelabel-controller
  namespace: system
  labels:
    control-plane: nodelabel-controller
    app.kubernetes.io/name: worker-group-claim-operator
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      control-plane: nodelabel-controller
      app.kubernetes.io/name: worker-group-claim-operator
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: nodelabel-controller
      labels:
        control-plane: nodelabel-controller
        app.kubernetes.io/name: worker-group-claim-operator
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - command:
        - /nodelabel-controller
        args:
        - --leader-elect
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=:8443
        - --observe-only=true
        - --remove-foreign-denied=false
        image: nodelabel-controller:latest
        name: nodelabel-controller
        ports: []
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 10m
            memory: 64Mi
        volumeMounts: []
      volumes: []
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
